name: build-flux-code-7b

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/build-flux-code-7b.yaml' # this file
    - 'flux-code-7b/**'
  workflow_dispatch: {}

permissions:
  contents: write
  id-token: write
  packages: write # needed for ghcr.io access

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download grype
      uses: anchore/scan-action/download-grype@v3
      id: grype
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Free disk space
      shell: bash
      run: |
        echo "=============================================================================="
        echo "Freeing up disk space on CI system"
        echo "=============================================================================="
        echo "Listing 100 largest packages"
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
        df -h
        echo "Removing large packages"
        # sudo apt-get remove -y '^ghc-8.*'
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-cli google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        df -h
        echo "Removing large directories"
        # deleting 15GB
        rm -rf /usr/share/dotnet/
        df -h
    - name: Scan base image
      run: |
        cd flux-code-7b/docker
        source ./VERSION
        ${{ steps.grype.outputs.cmd }} docker:ghcr.io/open-flux-ai/serve/llama-cpp-python:${IMAGE}-avx2
        #
        # TODO scan the GPU base image
        # ${{ steps.grype.outputs.cmd }} docker:ghcr.io/open-flux-ai/serve/llama-cpp-python:${IMAGE}-gpu
    - name: Build Flux Code 7B
      id: build-flux-code-7b
      run: |
        cd flux-code-7b/docker
        bash -x ./build.sh
